"""
Tests for the token-authenticated candidate interview flow (/api/candidate/sessions/*):
the invite link a recruiter sends a candidate, requiring no account.
"""

from tests.conftest import make_session


def _register(client, email="recruiter@example.com", password="longenough1"):
    res = client.post("/api/auth/register", json={"email": email, "password": password})
    assert res.status_code == 200, res.text
    return {"Authorization": f"Bearer {res.json()['access_token']}"}


def _create_with_invite(client, headers, mock_ai, **kwargs):
    """Creates a session and returns (session_id, invite_token)."""
    session_id = make_session(client, headers, mock_ai, **kwargs)
    res = client.get(f"/api/sessions/{session_id}", headers=headers)
    assert res.status_code == 200
    invite_url = res.json()["invite_url"]
    token = invite_url.split("token=")[1]
    return session_id, token


def test_create_session_returns_invite_url(client, mock_ai):
    headers = _register(client)
    files = {"resume": ("resume.pdf", b"%PDF-1.4 mock", "application/pdf")}
    data = {"candidate_name": "Ada Lovelace", "role": "ai_ml"}
    res = client.post("/api/sessions", data=data, files=files, headers=headers)
    assert res.status_code == 200
    assert "token=" in res.json()["invite_url"]


def test_candidate_can_complete_full_flow_with_token_only(client, mock_ai):
    """
    Answer submission is async (returns 202-style "processing" immediately, scores
    + advances in a FastAPI BackgroundTask). TestClient runs background tasks
    synchronously before returning the response, so by the time client.post()
    returns, the background work has already finished - no real polling needed
    here, just read the session back afterward.
    """
    from app.core.config import settings

    headers = _register(client, "recruiter2@example.com")
    session_id, token = _create_with_invite(client, headers, mock_ai)

    started = client.post(f"/api/candidate/sessions/{session_id}/start?token={token}")
    assert started.status_code == 200
    question = started.json()["question"]
    assert question["order"] == 1

    for _ in range(settings.MAX_QUESTIONS):
        res = client.post(
            f"/api/candidate/sessions/{session_id}/answers?token={token}&question_id={question['id']}",
            json={"answer_text": "A thorough, well-reasoned answer."},
        )
        assert res.status_code == 200
        body = res.json()
        # Candidate must never see a score, rationale, or the report in this response.
        assert body == {"status": "processing"}

        state = client.get(f"/api/candidate/sessions/{session_id}?token={token}").json()
        assert state["is_processing"] is False
        assert state["processing_error"] is None
        if state["status"] == "completed":
            break
        question = state["question"]

    final_state = client.get(f"/api/candidate/sessions/{session_id}?token={token}").json()
    assert final_state["status"] == "completed"
    # Candidate view must never include the report/recommendation.
    assert "report" not in final_state
    assert "recommendation" not in final_state

    # Recruiter, meanwhile, sees the full report - auto-generated by the last
    # answer's background task, no separate /complete call needed.
    full = client.get(f"/api/sessions/{session_id}", headers=headers)
    assert full.json()["report"]["recommendation"] == "yes"


def test_candidate_complete_endpoint_is_a_safe_noop_after_auto_completion(client, mock_ai):
    """The explicit /complete call is a fallback only - it must not create a
    second Report row when the background task already auto-completed."""
    from app.core.config import settings

    headers = _register(client, "recruiter2b@example.com")
    session_id, token = _create_with_invite(client, headers, mock_ai)

    started = client.post(f"/api/candidate/sessions/{session_id}/start?token={token}")
    question = started.json()["question"]

    for _ in range(settings.MAX_QUESTIONS):
        client.post(
            f"/api/candidate/sessions/{session_id}/answers?token={token}&question_id={question['id']}",
            json={"answer_text": "A thorough, well-reasoned answer."},
        )
        state = client.get(f"/api/candidate/sessions/{session_id}?token={token}").json()
        if state["status"] == "completed":
            break
        question = state["question"]

    completed = client.post(f"/api/candidate/sessions/{session_id}/complete?token={token}")
    assert completed.status_code == 200

    full = client.get(f"/api/sessions/{session_id}", headers=headers)
    assert full.json()["report"] is not None
    assert full.json()["report"]["recommendation"] == "yes"


def test_wrong_token_is_rejected(client, mock_ai):
    headers = _register(client, "recruiter3@example.com")
    session_id, _real_token = _create_with_invite(client, headers, mock_ai)

    res = client.get(f"/api/candidate/sessions/{session_id}?token=not-the-real-token")
    assert res.status_code == 404


def test_missing_token_is_rejected(client, mock_ai):
    headers = _register(client, "recruiter4@example.com")
    session_id, _token = _create_with_invite(client, headers, mock_ai)

    res = client.get(f"/api/candidate/sessions/{session_id}")
    assert res.status_code == 422  # required query param missing


def test_candidate_cannot_start_session_twice(client, mock_ai):
    headers = _register(client, "recruiter5@example.com")
    session_id, token = _create_with_invite(client, headers, mock_ai)

    first = client.post(f"/api/candidate/sessions/{session_id}/start?token={token}")
    assert first.status_code == 200

    second = client.post(f"/api/candidate/sessions/{session_id}/start?token={token}")
    assert second.status_code == 409


def test_recruiter_start_after_candidate_start_is_rejected(client, mock_ai):
    """Guards against a race: recruiter previewing after the candidate already began."""
    headers = _register(client, "recruiter6@example.com")
    session_id, token = _create_with_invite(client, headers, mock_ai)

    client.post(f"/api/candidate/sessions/{session_id}/start?token={token}")

    res = client.post(f"/api/sessions/{session_id}/start", headers=headers)
    assert res.status_code == 409


def test_submit_answer_while_already_processing_is_rejected(client, mock_ai, monkeypatch):
    """Guards against a double-submit race while a previous answer is still
    (supposedly) being graded - can't reuse the same in-flight slot."""
    import app.services.interview_orchestrator as orchestrator

    headers = _register(client, "recruiter8@example.com")
    session_id, token = _create_with_invite(client, headers, mock_ai)
    started = client.post(f"/api/candidate/sessions/{session_id}/start?token={token}")
    question_id = started.json()["question"]["id"]

    # Prevent the background task from ever clearing is_processing, so the second
    # submit attempt below finds the session still mid-flight.
    monkeypatch.setattr(orchestrator, "process_answer_in_background", lambda *a, **k: None)

    first = client.post(
        f"/api/candidate/sessions/{session_id}/answers?token={token}&question_id={question_id}",
        json={"answer_text": "First answer."},
    )
    assert first.status_code == 200

    second = client.post(
        f"/api/candidate/sessions/{session_id}/answers?token={token}&question_id={question_id}",
        json={"answer_text": "Second answer, while first is still processing."},
    )
    assert second.status_code == 409


def test_resend_invite_requires_candidate_email(client, mock_ai):
    headers = _register(client, "recruiter7@example.com")
    session_id = make_session(client, headers, mock_ai)  # no candidate_email passed

    res = client.post(f"/api/sessions/{session_id}/invite/send", headers=headers)
    assert res.status_code == 400
